import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/modules/auth_provider";
import WebSocketProvider from "@/modules/web_socket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <WebSocketProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </WebSocketProvider>
    </AuthContextProvider>
  );
}
